# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: My CloudBit API
  description: CloudBitの入力値を取得します
  version: "0.0.1"
# the domain of the service
host: thermometer-cloudbit-p150705.herokuapp.com
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
#basePath: /v1
produces:
  - application/json
paths:
  /input:
    get:
      summary: CloudBitの状態と入力値を取得
      description: |
        CloudBitの状態と入力値を取得します。
      parameters:
        - name: THERMO_CLOUDBIT_DEVICE_ID
          in: query
          description: デバイスID
          required: true
          type: string
          default: '00e04c032d62'
        - name: THERMO_CLOUDBIT_ACCESS_TOKEN
          in: query
          description: アクセストークン
          required: true
          type: string
          default: '04784c7ae09bea78704572648c547c472f61dfce0bdf00075fb050f85eaff8ab'
      tags:
        - Input
      responses:
        200:
          description: CloudBitの入力値と状態
          schema:
            type: array
            items:
              $ref: '#/definitions/Input'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Input:
    properties:
      type:
        type: string
        description: 入力と出力のどちらか
      timestamp: 
        type: number
        description: 日時
      from:
        type: object
        properties:
          socket:
            type: object
            properties:
              remotePort:
                type: number
                description: リモートホストのポート番号
              remoteAddress:
                type: string
              localAddress:
                type: string
              localPort:
                type: number
              id:
                type: string
          server:
            type: object
            properties:
              id:
                type: string
          user:
            type: object
            properties:
              id:
                type: number
          device:
            type: object
            properties:
              id:
                type: string
              device:
                type: string
              setup-version:
                type: string
              protocol_version:
                type: string
              firmware_version:
                type: string
              mac:
                type: string
              hash:
                type: string
              ap:
                type: object
                properties:
                  ssid:
                    type: string
                  mac:
                    type: string
                  strength:
                    type: number
              settings:
                type: object
                properties:
                  label:
                    type: string
                  input_interbal_ms:
                    type: number
          is_identified:
            type: boolean
      percent:
        type: number
        description: CloudBitの入力値です。この値がそのまま温度を示します。
      absolute:
        type: number
      name:
        type: string
      payload:
        type: object
        properties:
          percent:
            type: number
          absolute:
            type: number
  Error:
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
